forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/ntp'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/mysql'
mod 'puppetlabs/vcsrepo'
mod 'torrancew/cron'
mod 'adrien/network', '0.4.1'
mod 'python',
    :git => 'https://github.com/puppetmodules/puppet-module-python.git'
mod 'webapp',
    :git => 'https://github.com/puppetmodules/puppet-module-webapp.git'
mod 'monit',
    :git => 'https://github.com/puppetmodules/puppet-module-monit.git'
mod 'nginx',
    :git => 'https://github.com/puppetmodules/puppet-module-nginx.git'
